/*
 * The MIT License
 * 
 * Copyright: Copyright (C) 2014 T2Ti.COM
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 * The author may be contacted at: t2ti.com@gmail.com
 *
 * @author Claudio de Barros (T2Ti.com)
 * @version 2.0
 */
package com.t2tierp.conciliacaocontabil.cliente;

import com.t2tierp.cadastros.java.ClienteVO;
import com.t2tierp.contabilidade.java.ContabilLancamentoDetalheVO;
import com.t2tierp.financeiro.java.FinParcelaRecebimentoVO;
import java.util.List;
import javax.swing.ImageIcon;
import org.openswing.swing.client.GenericButton;
import org.openswing.swing.mdi.client.InternalFrame;
import org.openswing.swing.util.client.ClientUtils;

public class ConciliacaoClienteDetalhe extends InternalFrame {

    private LancamentoGridController lancamentoController;
    private ParcelaConciliacaoClienteGridController parcelaController;
    private LancamentoClienteConciliadoGridController conciliadoController;

    public ConciliacaoClienteDetalhe(ConciliacaoClienteDetalheController controller) {
        initComponents();

        formCliente.setFormController(controller);

        genericButton1.setToolTipText("Conciliar lançamentos");

        lancamentoController = new LancamentoGridController();
        gridLancamento.setController(lancamentoController);
        gridLancamento.setGridDataLocator(lancamentoController);
        gridLancamento.setShowFilterPanelOnGrid(false);

        parcelaController = new ParcelaConciliacaoClienteGridController();
        gridParcelaRecebimento.setController(parcelaController);
        gridParcelaRecebimento.setGridDataLocator(parcelaController);
        gridParcelaRecebimento.setShowFilterPanelOnGrid(false);

        conciliadoController = new LancamentoClienteConciliadoGridController(gridConciliado);
        gridConciliado.setShowFilterPanelOnGrid(false);
    }

    public org.openswing.swing.form.client.Form getFormCliente() {
        return formCliente;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formCliente = new org.openswing.swing.form.client.Form();
        labelControl1 = new org.openswing.swing.client.LabelControl();
        textControl2 = new org.openswing.swing.client.TextControl();
        textControl3 = new org.openswing.swing.client.TextControl();
        labelControl5 = new org.openswing.swing.client.LabelControl();
        jPanel3 = new javax.swing.JPanel();
        gridParcelaRecebimento = new org.openswing.swing.client.GridControl();
        dateColumn1 = new org.openswing.swing.table.columns.client.DateColumn();
        decimalColumn1 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn5 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn6 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn7 = new org.openswing.swing.table.columns.client.DecimalColumn();
        jPanel4 = new javax.swing.JPanel();
        gridLancamento = new org.openswing.swing.client.GridControl();
        textColumn4 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        decimalColumn2 = new org.openswing.swing.table.columns.client.DecimalColumn();
        comboColumn1 = new org.openswing.swing.table.columns.client.ComboColumn();
        jPanel5 = new javax.swing.JPanel();
        gridConciliado = new org.openswing.swing.client.GridControl();
        dateColumn2 = new org.openswing.swing.table.columns.client.DateColumn();
        decimalColumn3 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn8 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn9 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn10 = new org.openswing.swing.table.columns.client.DecimalColumn();
        textColumn9 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn10 = new org.openswing.swing.table.columns.client.TextColumn();
        decimalColumn4 = new org.openswing.swing.table.columns.client.DecimalColumn();
        comboColumn2 = new org.openswing.swing.table.columns.client.ComboColumn();
        jPanel6 = new javax.swing.JPanel();
        dateControl1 = new org.openswing.swing.client.DateControl();
        labelControl2 = new org.openswing.swing.client.LabelControl();
        dateControl2 = new org.openswing.swing.client.DateControl();
        labelControl3 = new org.openswing.swing.client.LabelControl();
        jLabel1 = new javax.swing.JLabel();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        genericButton1 = new GenericButton(new ImageIcon(ClientUtils.getImage("ok.gif")));

        setTitle("T2Ti ERP - Conciliacao Contábil");
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        formCliente.setVOClassName("com.t2tierp.cadastros.java.ClienteVO");
        formCliente.setLayout(new java.awt.GridBagLayout());

        labelControl1.setLabel("Nome Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        formCliente.add(labelControl1, gridBagConstraints);

        textControl2.setAttributeName("pessoa.nome");
        textControl2.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        formCliente.add(textControl2, gridBagConstraints);

        textControl3.setAttributeName("contabilConta.descricao");
        textControl3.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        formCliente.add(textControl3, gridBagConstraints);

        labelControl5.setLabel("Conta Contabil:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        formCliente.add(labelControl5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(formCliente, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas Recebidas"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        gridParcelaRecebimento.setAutoLoadData(false);
        gridParcelaRecebimento.setShowPageNumber(false);
        gridParcelaRecebimento.setValueObjectClassName("com.t2tierp.financeiro.java.FinParcelaRecebimentoVO");
        gridParcelaRecebimento.setVisibleStatusPanel(false);
        gridParcelaRecebimento.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        dateColumn1.setColumnName("dataRecebimento");
        dateColumn1.setHeaderColumnName("Data Recebimento");
        dateColumn1.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        dateColumn1.setPreferredWidth(120);
        gridParcelaRecebimento.getColumnContainer().add(dateColumn1);

        decimalColumn1.setColumnName("valorJuro");
        decimalColumn1.setDecimals(2);
        decimalColumn1.setHeaderColumnName("Juros");
        decimalColumn1.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridParcelaRecebimento.getColumnContainer().add(decimalColumn1);

        decimalColumn5.setColumnName("valorMulta");
        decimalColumn5.setDecimals(2);
        decimalColumn5.setHeaderColumnName("Multa");
        decimalColumn5.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridParcelaRecebimento.getColumnContainer().add(decimalColumn5);

        decimalColumn6.setColumnName("valorDesconto");
        decimalColumn6.setDecimals(2);
        decimalColumn6.setHeaderColumnName("Desconto");
        decimalColumn6.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridParcelaRecebimento.getColumnContainer().add(decimalColumn6);

        decimalColumn7.setColumnName("valorRecebido");
        decimalColumn7.setDecimals(2);
        decimalColumn7.setHeaderColumnName("Valor Recebido");
        decimalColumn7.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridParcelaRecebimento.getColumnContainer().add(decimalColumn7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(gridParcelaRecebimento, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamentos Contábeis"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        gridLancamento.setAutoLoadData(false);
        gridLancamento.setShowPageNumber(false);
        gridLancamento.setValueObjectClassName("com.t2tierp.contabilidade.java.ContabilLancamentoDetalheVO");
        gridLancamento.setVisibleStatusPanel(false);
        gridLancamento.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        textColumn4.setColumnName("contabilConta.descricao");
        textColumn4.setHeaderColumnName("Conta");
        textColumn4.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridLancamento.getColumnContainer().add(textColumn4);

        textColumn5.setColumnName("historico");
        textColumn5.setHeaderColumnName("Historico");
        textColumn5.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridLancamento.getColumnContainer().add(textColumn5);

        decimalColumn2.setColumnName("valor");
        decimalColumn2.setDecimals(2);
        decimalColumn2.setHeaderColumnName("Valor");
        decimalColumn2.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridLancamento.getColumnContainer().add(decimalColumn2);

        comboColumn1.setColumnName("tipo");
        comboColumn1.setDomainId("tipoLancamento");
        comboColumn1.setHeaderColumnName("Tipo");
        comboColumn1.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridLancamento.getColumnContainer().add(comboColumn1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(gridLancamento, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Lançamentos Conciliados"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        gridConciliado.setAutoLoadData(false);
        gridConciliado.setShowPageNumber(false);
        gridConciliado.setValueObjectClassName("com.t2tierp.conciliacaocontabil.java.ConciliacaoClienteVO");
        gridConciliado.setVisibleStatusPanel(false);
        gridConciliado.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        dateColumn2.setColumnName("parcelaDataRecebimento");
        dateColumn2.setHeaderColumnName("Data Recebimento");
        dateColumn2.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridConciliado.getColumnContainer().add(dateColumn2);

        decimalColumn3.setColumnName("parcelaValorJuro");
        decimalColumn3.setDecimals(2);
        decimalColumn3.setHeaderColumnName("Juros");
        decimalColumn3.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridConciliado.getColumnContainer().add(decimalColumn3);

        decimalColumn8.setColumnName("parcelaValorMulta");
        decimalColumn8.setDecimals(2);
        decimalColumn8.setHeaderColumnName("Multa");
        decimalColumn8.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridConciliado.getColumnContainer().add(decimalColumn8);

        decimalColumn9.setColumnName("parcelaValorDesconto");
        decimalColumn9.setDecimals(2);
        decimalColumn9.setHeaderColumnName("Desconto");
        decimalColumn9.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridConciliado.getColumnContainer().add(decimalColumn9);

        decimalColumn10.setColumnName("parcelaValorPago");
        decimalColumn10.setDecimals(2);
        decimalColumn10.setHeaderColumnName("Valor Pago");
        decimalColumn10.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridConciliado.getColumnContainer().add(decimalColumn10);

        textColumn9.setColumnName("lancamentoContabilConta.descricao");
        textColumn9.setHeaderColumnName("Conta");
        textColumn9.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridConciliado.getColumnContainer().add(textColumn9);

        textColumn10.setColumnName("lancamentoHistorico");
        textColumn10.setHeaderColumnName("Historico Lancamento");
        textColumn10.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumn10.setPreferredWidth(150);
        gridConciliado.getColumnContainer().add(textColumn10);

        decimalColumn4.setColumnName("lancamentoValor");
        decimalColumn4.setDecimals(2);
        decimalColumn4.setHeaderColumnName("Valor Lancamento");
        decimalColumn4.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        decimalColumn4.setPreferredWidth(120);
        gridConciliado.getColumnContainer().add(decimalColumn4);

        comboColumn2.setColumnName("lancamentoTipo");
        comboColumn2.setDomainId("tipoLancamento");
        comboColumn2.setHeaderColumnName("Tipo");
        comboColumn2.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridConciliado.getColumnContainer().add(comboColumn2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(gridConciliado, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel5, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel6.add(dateControl1, gridBagConstraints);

        labelControl2.setLabel("Período de:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel6.add(labelControl2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel6.add(dateControl2, gridBagConstraints);

        labelControl3.setLabel("a:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel6.add(labelControl3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel6.add(jLabel1, gridBagConstraints);

        reloadButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel6.add(reloadButton1, gridBagConstraints);

        genericButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genericButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel6.add(genericButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel6, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButton1ActionPerformed
        ClienteVO cliente = (ClienteVO) getFormCliente().getVOModel().getValueObject();
        parcelaController.setDataInicial(dateControl1.getDate());
        parcelaController.setDataFinal(dateControl2.getDate());
        parcelaController.setCliente(cliente);
        gridParcelaRecebimento.reloadData();

        lancamentoController.setDataInicial(dateControl1.getDate());
        lancamentoController.setDataFinal(dateControl2.getDate());
        gridLancamento.reloadData();

    }//GEN-LAST:event_reloadButton1ActionPerformed

    private void genericButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genericButton1ActionPerformed
        List<FinParcelaRecebimentoVO> listaParcelas = gridParcelaRecebimento.getVOListTableModel().getDataVector();
        List<ContabilLancamentoDetalheVO> listaLancamentos = gridLancamento.getVOListTableModel().getDataVector();
        conciliadoController.conciliaLancamentos(listaParcelas, listaLancamentos);
    }//GEN-LAST:event_genericButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn1;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn2;
    private org.openswing.swing.table.columns.client.DateColumn dateColumn1;
    private org.openswing.swing.table.columns.client.DateColumn dateColumn2;
    private org.openswing.swing.client.DateControl dateControl1;
    private org.openswing.swing.client.DateControl dateControl2;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn1;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn10;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn2;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn3;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn4;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn5;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn6;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn7;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn8;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn9;
    private org.openswing.swing.form.client.Form formCliente;
    private org.openswing.swing.client.GenericButton genericButton1;
    private org.openswing.swing.client.GridControl gridConciliado;
    private org.openswing.swing.client.GridControl gridLancamento;
    private org.openswing.swing.client.GridControl gridParcelaRecebimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private org.openswing.swing.client.LabelControl labelControl1;
    private org.openswing.swing.client.LabelControl labelControl2;
    private org.openswing.swing.client.LabelControl labelControl3;
    private org.openswing.swing.client.LabelControl labelControl5;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn10;
    private org.openswing.swing.table.columns.client.TextColumn textColumn4;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    private org.openswing.swing.table.columns.client.TextColumn textColumn9;
    private org.openswing.swing.client.TextControl textControl2;
    private org.openswing.swing.client.TextControl textControl3;
    // End of variables declaration//GEN-END:variables

}
