/*
 * The MIT License
 * 
 * Copyright: Copyright (C) 2014 T2Ti.COM
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 * The author may be contacted at: t2ti.com@gmail.com
 *
 * @author Claudio de Barros (T2Ti.com)
 * @version 2.0
 */
package com.t2tierp.nfe.cliente;

import org.openswing.swing.client.GridControl;
import org.openswing.swing.mdi.client.InternalFrame;

public class NfeGrid extends InternalFrame {

    public NfeGrid(NfeGridController controller) {
        initComponents();
        gridControl1.setController(controller);
        gridControl1.setGridDataLocator(controller);
    }

    public GridControl getGrid1() {
        return gridControl1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        gridControl1 = new org.openswing.swing.client.GridControl();
        textColumn2 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn6 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn8 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn13 = new org.openswing.swing.table.columns.client.TextColumn();
        dateColumn14 = new org.openswing.swing.table.columns.client.DateColumn();
        comboColumn17 = new org.openswing.swing.table.columns.client.ComboColumn();
        textColumn21 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        decimalColumn33 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn34 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn36 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn42 = new org.openswing.swing.table.columns.client.DecimalColumn();
        comboColumn62 = new org.openswing.swing.table.columns.client.ComboColumn();

        setTitle("T2Ti ERP - NF-e - Nota Fiscal Eletrônica");
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nfe Cabecalho"));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(insertButton1);
        jPanel1.add(reloadButton1);
        jPanel1.add(navigatorBar1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        gridControl1.setFunctionId("nfeCabecalho");
        gridControl1.setInsertButton(insertButton1);
        gridControl1.setNavBar(navigatorBar1);
        gridControl1.setReloadButton(reloadButton1);
        gridControl1.setValueObjectClassName("com.t2tierp.nfe.java.NfeCabecalhoVO");
        gridControl1.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        textColumn2.setColumnName("tributOperacaoFiscal.descricao");
        textColumn2.setHeaderColumnName("Operacao Fiscal");
        textColumn2.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumn2.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn2);

        textColumn5.setColumnName("fornecedor.pessoa.nome");
        textColumn5.setHeaderColumnName("Fornecedor");
        textColumn5.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumn5.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn5);

        textColumn6.setColumnName("cliente.pessoa.nome");
        textColumn6.setHeaderColumnName("Cliente");
        textColumn6.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumn6.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn6);

        textColumn8.setColumnName("codigoNumerico");
        textColumn8.setHeaderColumnName("Codigo Numerico");
        textColumn8.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(textColumn8);

        textColumn13.setColumnFilterable(true);
        textColumn13.setColumnName("numero");
        textColumn13.setHeaderColumnName("Numero");
        textColumn13.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(textColumn13);

        dateColumn14.setColumnFilterable(true);
        dateColumn14.setColumnName("dataHoraEmissao");
        dateColumn14.setHeaderColumnName("Data Emissao");
        dateColumn14.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(dateColumn14);

        comboColumn17.setColumnName("tipoOperacao");
        comboColumn17.setDomainId("tipoOperacao");
        comboColumn17.setHeaderColumnName("Tipo Operacao");
        comboColumn17.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(comboColumn17);

        textColumn21.setColumnName("chaveAcesso");
        textColumn21.setHeaderColumnName("Chave Acesso");
        textColumn21.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumn21.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn21);

        textColumn1.setColumnName("digitoChaveAcesso");
        textColumn1.setHeaderColumnName("DV Chave Acesso");
        textColumn1.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(textColumn1);

        decimalColumn33.setColumnName("valorTotalProdutos");
        decimalColumn33.setDecimals(2);
        decimalColumn33.setHeaderColumnName("Valor Total Produtos");
        decimalColumn33.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        decimalColumn33.setPreferredWidth(120);
        gridControl1.getColumnContainer().add(decimalColumn33);

        decimalColumn34.setColumnName("valorFrete");
        decimalColumn34.setHeaderColumnName("Valor Frete");
        decimalColumn34.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        decimalColumn34.setDecimals(2);
        gridControl1.getColumnContainer().add(decimalColumn34);

        decimalColumn36.setColumnName("valorDesconto");
        decimalColumn36.setHeaderColumnName("Valor Desconto");
        decimalColumn36.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        decimalColumn36.setDecimals(2);
        gridControl1.getColumnContainer().add(decimalColumn36);

        decimalColumn42.setColumnName("valorTotal");
        decimalColumn42.setHeaderColumnName("Valor Total");
        decimalColumn42.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        decimalColumn42.setDecimals(2);
        gridControl1.getColumnContainer().add(decimalColumn42);

        comboColumn62.setColumnName("statusNota");
        comboColumn62.setDomainId("statusNotaFiscalEletronica");
        comboColumn62.setHeaderColumnName("Status Nota");
        comboColumn62.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridControl1.getColumnContainer().add(comboColumn62);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn17;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn62;
    private org.openswing.swing.table.columns.client.DateColumn dateColumn14;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn33;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn34;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn36;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn42;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.InsertButton insertButton1;
    private javax.swing.JPanel jPanel1;
    private org.openswing.swing.client.NavigatorBar navigatorBar1;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn13;
    private org.openswing.swing.table.columns.client.TextColumn textColumn2;
    private org.openswing.swing.table.columns.client.TextColumn textColumn21;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    private org.openswing.swing.table.columns.client.TextColumn textColumn6;
    private org.openswing.swing.table.columns.client.TextColumn textColumn8;
    // End of variables declaration//GEN-END:variables
}
