/*
 * The MIT License
 * 
 * Copyright: Copyright (C) 2014 T2Ti.COM
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 * The author may be contacted at: t2ti.com@gmail.com
 *
 * @author Claudio de Barros (T2Ti.com)
 * @version 2.0
 */
package com.t2tierp.compras.cliente;

import org.openswing.swing.mdi.client.InternalFrame;

public class CompraMapaComparativoDetalhe extends InternalFrame {

    private CompraFornecedorMapaComparativoGridController fornecedorController;
    private CompraMapaComparativoDetalheGridController mapaComparativoDetalheGridController;

    public CompraMapaComparativoDetalhe(CompraMapaComparativoDetalheController controller) {
        initComponents();

        form1.setFormController(controller);

        fornecedorController = new CompraFornecedorMapaComparativoGridController();
        gridFornecedor.setController(fornecedorController);
        gridFornecedor.setGridDataLocator(fornecedorController);

        mapaComparativoDetalheGridController = new CompraMapaComparativoDetalheGridController(this);
        gridItensCotacao.setController(mapaComparativoDetalheGridController);
        gridItensCotacao.setGridDataLocator(mapaComparativoDetalheGridController);

    }

    /**
     * @return the form1
     */
    public org.openswing.swing.form.client.Form getForm1() {
        return form1;
    }

    /**
     * @return the gridFornecedor
     */
    public org.openswing.swing.client.GridControl getGridFornecedor() {
        return gridFornecedor;
    }

    /**
     * @return the gridItensCotacao
     */
    public org.openswing.swing.client.GridControl getGridItensCotacao() {
        return gridItensCotacao;
    }

    /**
     * @return the fornecedorCotacaoController
     */
    public CompraFornecedorMapaComparativoGridController getFornecedorMapaComparativoController() {
        return fornecedorController;
    }

    /**
     * @return the cotacaoDetalheController
     */
    public CompraMapaComparativoDetalheGridController getMapaComparativoDetalheController() {
        return mapaComparativoDetalheGridController;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        saveButton1 = new org.openswing.swing.client.SaveButton();
        form1 = new org.openswing.swing.form.client.Form();
        labelControl1 = new org.openswing.swing.client.LabelControl();
        dateControl2 = new org.openswing.swing.client.DateControl();
        labelControl2 = new org.openswing.swing.client.LabelControl();
        textControl3 = new org.openswing.swing.client.TextControl();
        labelControl3 = new org.openswing.swing.client.LabelControl();
        comboBoxControl4 = new org.openswing.swing.client.ComboBoxControl();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        reloadButtonFornecedor = new org.openswing.swing.client.ReloadButton();
        navigatorBarFornecedor = new org.openswing.swing.client.NavigatorBar();
        gridFornecedor = new org.openswing.swing.client.GridControl();
        textColumn7 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn6 = new org.openswing.swing.table.columns.client.TextColumn();
        decimalColumn7 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn8 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn9 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn10 = new org.openswing.swing.table.columns.client.DecimalColumn();
        jPanel5 = new javax.swing.JPanel();
        editButtonItens = new org.openswing.swing.client.EditButton();
        saveButtonItens = new org.openswing.swing.client.SaveButton();
        reloadButtonItens = new org.openswing.swing.client.ReloadButton();
        navigatorBarItens = new org.openswing.swing.client.NavigatorBar();
        gridItensCotacao = new org.openswing.swing.client.GridControl();
        textColumn8 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn4 = new org.openswing.swing.table.columns.client.TextColumn();
        decimalColumn6 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn16 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn11 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn12 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn13 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn14 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn15 = new org.openswing.swing.table.columns.client.DecimalColumn();

        setTitle("T2Ti ERP - Gestão de Compras");
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Compra Mapa Comparativo"));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(reloadButton1);
        jPanel1.add(saveButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        form1.setVOClassName("com.t2tierp.compras.java.CompraCotacaoVO");
        form1.setFunctionId("compraCotacao");
        form1.setReloadButton(reloadButton1);
        form1.setSaveButton(saveButton1);
        form1.setLayout(new java.awt.GridBagLayout());

        labelControl1.setLabel("Data Cotacao:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(labelControl1, gridBagConstraints);

        dateControl2.setAttributeName("dataCotacao");
        dateControl2.setEnabled(false);
        dateControl2.setEnabledOnEdit(false);
        dateControl2.setEnabledOnInsert(false);
        dateControl2.setLinkLabel(labelControl1);
        dateControl2.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        form1.add(dateControl2, gridBagConstraints);

        labelControl2.setLabel("Descricao:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(labelControl2, gridBagConstraints);

        textControl3.setAttributeName("descricao");
        textControl3.setEnabled(false);
        textControl3.setEnabledOnEdit(false);
        textControl3.setEnabledOnInsert(false);
        textControl3.setLinkLabel(labelControl2);
        textControl3.setMaxCharacters(100);
        textControl3.setRequired(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        form1.add(textControl3, gridBagConstraints);

        labelControl3.setLabel("Situacao:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        form1.add(labelControl3, gridBagConstraints);

        comboBoxControl4.setAttributeName("situacao");
        comboBoxControl4.setDomainId("compraSituacaoCotacao");
        comboBoxControl4.setEnabled(false);
        comboBoxControl4.setEnabledOnEdit(false);
        comboBoxControl4.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        form1.add(comboBoxControl4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(form1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Compra Fornecedor Cotacao"));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel3.add(reloadButtonFornecedor);
        jPanel3.add(navigatorBarFornecedor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jPanel3, gridBagConstraints);

        gridFornecedor.setAutoLoadData(false);
        gridFornecedor.setFunctionId("compraFornecedorConfirmaCotacao");
        gridFornecedor.setNavBar(navigatorBarFornecedor);
        gridFornecedor.setReloadButton(reloadButtonFornecedor);
        gridFornecedor.setValueObjectClassName("com.t2tierp.compras.java.CompraFornecedorCotacaoVO");
        gridFornecedor.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        textColumn7.setColumnName("fornecedor.pessoa.nome");
        textColumn7.setHeaderColumnName("Fornecedor");
        textColumn7.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumn7.setPreferredWidth(200);
        gridFornecedor.getColumnContainer().add(textColumn7);

        textColumn5.setColumnName("prazoEntrega");
        textColumn5.setColumnRequired(false);
        textColumn5.setHeaderColumnName("Prazo Entrega");
        textColumn5.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridFornecedor.getColumnContainer().add(textColumn5);

        textColumn6.setColumnName("condicoesPagamento");
        textColumn6.setColumnRequired(false);
        textColumn6.setHeaderColumnName("Condicoes Pagamento");
        textColumn6.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumn6.setPreferredWidth(130);
        gridFornecedor.getColumnContainer().add(textColumn6);

        decimalColumn7.setColumnName("valorSubtotal");
        decimalColumn7.setDecimals(2);
        decimalColumn7.setHeaderColumnName("Valor Subtotal");
        decimalColumn7.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridFornecedor.getColumnContainer().add(decimalColumn7);

        decimalColumn8.setColumnName("taxaDesconto");
        decimalColumn8.setDecimals(2);
        decimalColumn8.setHeaderColumnName("Taxa Desconto");
        decimalColumn8.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridFornecedor.getColumnContainer().add(decimalColumn8);

        decimalColumn9.setColumnName("valorDesconto");
        decimalColumn9.setDecimals(2);
        decimalColumn9.setHeaderColumnName("Valor Desconto");
        decimalColumn9.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridFornecedor.getColumnContainer().add(decimalColumn9);

        decimalColumn10.setColumnName("total");
        decimalColumn10.setDecimals(2);
        decimalColumn10.setHeaderColumnName("Total");
        decimalColumn10.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridFornecedor.getColumnContainer().add(decimalColumn10);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(gridFornecedor, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel5.add(editButtonItens);
        jPanel5.add(saveButtonItens);
        jPanel5.add(reloadButtonItens);
        jPanel5.add(navigatorBarItens);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jPanel5, gridBagConstraints);

        gridItensCotacao.setAutoLoadData(false);
        gridItensCotacao.setEditButton(editButtonItens);
        gridItensCotacao.setFunctionId("compraConfirmaCotacaoDetalhe");
        gridItensCotacao.setNavBar(navigatorBarItens);
        gridItensCotacao.setReloadButton(reloadButtonItens);
        gridItensCotacao.setSaveButton(saveButtonItens);
        gridItensCotacao.setValueObjectClassName("com.t2tierp.compras.java.CompraCotacaoDetalheVO");
        gridItensCotacao.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        textColumn8.setColumnName("compraFornecedorCotacao.fornecedor.pessoa.nome");
        textColumn8.setColumnRequired(false);
        textColumn8.setHeaderColumnName("Fornecedor");
        textColumn8.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumn8.setPreferredWidth(200);
        gridItensCotacao.getColumnContainer().add(textColumn8);

        textColumn4.setColumnName("produto.nome");
        textColumn4.setColumnRequired(false);
        textColumn4.setHeaderColumnName("Produto");
        textColumn4.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        textColumn4.setPreferredWidth(200);
        gridItensCotacao.getColumnContainer().add(textColumn4);

        decimalColumn6.setColumnName("quantidade");
        decimalColumn6.setColumnRequired(false);
        decimalColumn6.setDecimals(2);
        decimalColumn6.setHeaderColumnName("Quantidade");
        decimalColumn6.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        decimalColumn6.setPreferredWidth(90);
        gridItensCotacao.getColumnContainer().add(decimalColumn6);

        decimalColumn16.setColumnName("quantidadePedida");
        decimalColumn16.setDecimals(2);
        decimalColumn16.setEditableOnEdit(true);
        decimalColumn16.setEditableOnInsert(true);
        decimalColumn16.setHeaderColumnName("Quantidade Pedida");
        decimalColumn16.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        decimalColumn16.setPreferredWidth(120);
        gridItensCotacao.getColumnContainer().add(decimalColumn16);

        decimalColumn11.setColumnName("valorUnitario");
        decimalColumn11.setColumnRequired(false);
        decimalColumn11.setDecimals(2);
        decimalColumn11.setHeaderColumnName("Valor Unitario");
        decimalColumn11.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridItensCotacao.getColumnContainer().add(decimalColumn11);

        decimalColumn12.setColumnName("valorSubtotal");
        decimalColumn12.setColumnRequired(false);
        decimalColumn12.setDecimals(2);
        decimalColumn12.setHeaderColumnName("Valor Subtotal");
        decimalColumn12.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridItensCotacao.getColumnContainer().add(decimalColumn12);

        decimalColumn13.setColumnName("taxaDesconto");
        decimalColumn13.setColumnRequired(false);
        decimalColumn13.setDecimals(2);
        decimalColumn13.setHeaderColumnName("Taxa Desconto");
        decimalColumn13.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridItensCotacao.getColumnContainer().add(decimalColumn13);

        decimalColumn14.setColumnName("valorDesconto");
        decimalColumn14.setColumnRequired(false);
        decimalColumn14.setDecimals(2);
        decimalColumn14.setHeaderColumnName("Valor Desconto");
        decimalColumn14.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridItensCotacao.getColumnContainer().add(decimalColumn14);

        decimalColumn15.setColumnName("valorTotal");
        decimalColumn15.setColumnRequired(false);
        decimalColumn15.setDecimals(2);
        decimalColumn15.setHeaderColumnName("Valor Total");
        decimalColumn15.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gridItensCotacao.getColumnContainer().add(decimalColumn15);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(gridItensCotacao, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.ComboBoxControl comboBoxControl4;
    private org.openswing.swing.client.DateControl dateControl2;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn10;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn11;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn12;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn13;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn14;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn15;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn16;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn6;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn7;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn8;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn9;
    private org.openswing.swing.client.EditButton editButtonItens;
    private org.openswing.swing.form.client.Form form1;
    private org.openswing.swing.client.GridControl gridFornecedor;
    private org.openswing.swing.client.GridControl gridItensCotacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private org.openswing.swing.client.LabelControl labelControl1;
    private org.openswing.swing.client.LabelControl labelControl2;
    private org.openswing.swing.client.LabelControl labelControl3;
    private org.openswing.swing.client.NavigatorBar navigatorBarFornecedor;
    private org.openswing.swing.client.NavigatorBar navigatorBarItens;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.client.ReloadButton reloadButtonFornecedor;
    private org.openswing.swing.client.ReloadButton reloadButtonItens;
    private org.openswing.swing.client.SaveButton saveButton1;
    private org.openswing.swing.client.SaveButton saveButtonItens;
    private org.openswing.swing.table.columns.client.TextColumn textColumn4;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    private org.openswing.swing.table.columns.client.TextColumn textColumn6;
    private org.openswing.swing.table.columns.client.TextColumn textColumn7;
    private org.openswing.swing.table.columns.client.TextColumn textColumn8;
    private org.openswing.swing.client.TextControl textControl3;
    // End of variables declaration//GEN-END:variables

}
