/*
 * The MIT License
 * 
 * Copyright: Copyright (C) 2014 T2Ti.COM
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 * The author may be contacted at: t2ti.com@gmail.com
 *
 * @author Claudio de Barros (T2Ti.com)
 * @version 2.0
 */
package com.t2tierp.financeiro.cliente;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import org.openswing.swing.client.GridControl;
import org.openswing.swing.mdi.client.InternalFrame;

public class FinFluxoCaixaDetalhe extends InternalFrame {

    private FinFluxoCaixaDetalheController controller;
    private DecimalFormat decimalFormat = new DecimalFormat("#,###,##0.00");

    public FinFluxoCaixaDetalhe(FinFluxoCaixaDetalheController controller) {
        initComponents();
        this.controller = controller;
        gridControl1.setController(controller);
        gridControl1.setGridDataLocator(controller);
    }

    public GridControl getGrid1() {
        return gridControl1;
    }

    public void setTextoContaCaixa(String nomeContaCaixa){
        lblContaCaixa.setText("Conta Caixa: " + nomeContaCaixa);
    }

    public void setTextoPeriodo(String periodo){
        lblPeriodo.setText("Período: " + periodo);
    }

    public void setTextoRecebimentos(BigDecimal valor){
        lblRecebimentos.setText("|   A Receber: R$ " + decimalFormat.format(valor));
    }

    public void setTextoPagamentos(BigDecimal valor){
        lblPagamentos.setText("|   A Pagar: R$ " + decimalFormat.format(valor));
    }

    public void setTextoSaldo(BigDecimal valor){
        lblSaldo.setText("|   Saldo: R$ " + decimalFormat.format(valor) + "   |");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        gridControl1 = new org.openswing.swing.client.GridControl();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn2 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn3 = new org.openswing.swing.table.columns.client.TextColumn();
        dateColumn1 = new org.openswing.swing.table.columns.client.DateColumn();
        dateColumn2 = new org.openswing.swing.table.columns.client.DateColumn();
        decimalColumn1 = new org.openswing.swing.table.columns.client.DecimalColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        jPanel4 = new javax.swing.JPanel();
        lblContaCaixa = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblRecebimentos = new javax.swing.JLabel();
        lblPagamentos = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();

        setTitle("T2Ti ERP - Financeiro - Fluxo de Caixa");
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.CardLayout());

        gridControl1.setAutoLoadData(false);
        gridControl1.setValueObjectClassName("com.t2tierp.financeiro.java.ViewFinFluxoCaixaID");
        gridControl1.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        textColumn1.setColumnName("viewFinFluxoCaixa.operacao");
        textColumn1.setHeaderColumnName("Operacao");
        textColumn1.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        textColumn1.setPreferredWidth(60);
        gridControl1.getColumnContainer().add(textColumn1);

        textColumn2.setColumnName("viewFinFluxoCaixa.nomeContaCaixa");
        textColumn2.setHeaderColumnName("Conta Caixa");
        textColumn2.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        textColumn2.setPreferredWidth(200);
        gridControl1.getColumnContainer().add(textColumn2);

        textColumn3.setColumnName("viewFinFluxoCaixa.nomePessoa");
        textColumn3.setHeaderColumnName("Pessoa");
        textColumn3.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        textColumn3.setPreferredWidth(300);
        gridControl1.getColumnContainer().add(textColumn3);

        dateColumn1.setColumnName("viewFinFluxoCaixa.dataLancamento");
        dateColumn1.setHeaderColumnName("Data Lancamento");
        dateColumn1.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        gridControl1.getColumnContainer().add(dateColumn1);

        dateColumn2.setColumnName("viewFinFluxoCaixa.dataVencimento");
        dateColumn2.setHeaderColumnName("Data Pago/Recebido");
        dateColumn2.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        dateColumn2.setPreferredWidth(120);
        gridControl1.getColumnContainer().add(dateColumn2);

        decimalColumn1.setColumnName("viewFinFluxoCaixa.valor");
        decimalColumn1.setDecimals(2);
        decimalColumn1.setHeaderColumnName("Valor");
        decimalColumn1.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        gridControl1.getColumnContainer().add(decimalColumn1);

        textColumn5.setColumnName("viewFinFluxoCaixa.descricaoSituacao");
        textColumn5.setHeaderColumnName("Situacao");
        textColumn5.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        gridControl1.getColumnContainer().add(textColumn5);

        jPanel3.add(gridControl1, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fin Fluxo Caixa"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        lblContaCaixa.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblContaCaixa.setText("Conta Caixa: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(lblContaCaixa, gridBagConstraints);

        lblPeriodo.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblPeriodo.setText("Período: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(lblPeriodo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel4, gridBagConstraints);

        lblRecebimentos.setFont(new java.awt.Font("Arial", 1, 14));
        lblRecebimentos.setText("|   A Receber:");
        jPanel1.add(lblRecebimentos);

        lblPagamentos.setFont(new java.awt.Font("Arial", 1, 14));
        lblPagamentos.setText("|   A Pagar:");
        jPanel1.add(lblPagamentos);

        lblSaldo.setFont(new java.awt.Font("Arial", 1, 14));
        lblSaldo.setText("|   Saldo:   |");
        jPanel1.add(lblSaldo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.DateColumn dateColumn1;
    private org.openswing.swing.table.columns.client.DateColumn dateColumn2;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn1;
    private org.openswing.swing.client.GridControl gridControl1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblContaCaixa;
    private javax.swing.JLabel lblPagamentos;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblRecebimentos;
    private javax.swing.JLabel lblSaldo;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn2;
    private org.openswing.swing.table.columns.client.TextColumn textColumn3;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    // End of variables declaration//GEN-END:variables

}
