/*
 * The MIT License
 * 
 * Copyright: Copyright (C) 2014 T2Ti.COM
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * 
 * The author may be contacted at: t2ti.com@gmail.com
 *
 * @author Claudio de Barros (T2Ti.com)
 * @version 2.0
 */
package com.t2tierp.ponto.cliente;

import org.openswing.swing.client.GridControl;
import org.openswing.swing.mdi.client.InternalFrame;

public class PontoParametroGrid extends InternalFrame {

    public PontoParametroGrid(PontoParametroGridController controller) {
        initComponents();
        gridControl1.setController(controller);
        gridControl1.setGridDataLocator(controller);
    }

    public GridControl getGrid1() {
        return gridControl1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        gridControl1 = new org.openswing.swing.client.GridControl();
        textColumn3 = new org.openswing.swing.table.columns.client.TextColumn();
        integerColumn4 = new org.openswing.swing.table.columns.client.IntegerColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn6 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn7 = new org.openswing.swing.table.columns.client.TextColumn();
        decimalColumn8 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn9 = new org.openswing.swing.table.columns.client.DecimalColumn();
        textColumn10 = new org.openswing.swing.table.columns.client.TextColumn();
        comboColumn11 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn12 = new org.openswing.swing.table.columns.client.ComboColumn();

        setTitle("T2Ti ERP - Ponto Eletrônico");
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ponto Parametro"));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(insertButton1);
        jPanel1.add(deleteButton1);
        jPanel1.add(reloadButton1);
        jPanel1.add(navigatorBar1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        gridControl1.setDeleteButton(deleteButton1);
        gridControl1.setFunctionId("pontoParametro");
        gridControl1.setInsertButton(insertButton1);
        gridControl1.setNavBar(navigatorBar1);
        gridControl1.setReloadButton(reloadButton1);
        gridControl1.setValueObjectClassName("com.t2tierp.ponto.java.PontoParametroVO");
        gridControl1.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        textColumn3.setColumnName("mesAno");
        textColumn3.setHeaderColumnName("Mes Ano");
        textColumn3.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        gridControl1.getColumnContainer().add(textColumn3);

        integerColumn4.setColumnName("diaInicialApuracao");
        integerColumn4.setHeaderColumnName("Dia Inicial Apuracao");
        integerColumn4.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        integerColumn4.setPreferredWidth(110);
        gridControl1.getColumnContainer().add(integerColumn4);

        textColumn5.setColumnName("horaNoturnaInicio");
        textColumn5.setHeaderColumnName("Hora Noturna Inicio");
        textColumn5.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        textColumn5.setPreferredWidth(110);
        gridControl1.getColumnContainer().add(textColumn5);

        textColumn6.setColumnName("horaNoturnaFim");
        textColumn6.setHeaderColumnName("Hora Noturna Fim");
        textColumn6.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        gridControl1.getColumnContainer().add(textColumn6);

        textColumn7.setColumnName("periodoMinimoInterjornada");
        textColumn7.setHeaderColumnName("Periodo Minimo Interjornada");
        textColumn7.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        textColumn7.setPreferredWidth(170);
        gridControl1.getColumnContainer().add(textColumn7);

        decimalColumn8.setColumnName("percentualHeDiurna");
        decimalColumn8.setDecimals(2);
        decimalColumn8.setHeaderColumnName("Percentual He Diurna");
        decimalColumn8.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        decimalColumn8.setPreferredWidth(120);
        gridControl1.getColumnContainer().add(decimalColumn8);

        decimalColumn9.setColumnName("percentualHeNoturna");
        decimalColumn9.setDecimals(2);
        decimalColumn9.setHeaderColumnName("Percentual He Noturna");
        decimalColumn9.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        decimalColumn9.setPreferredWidth(130);
        gridControl1.getColumnContainer().add(decimalColumn9);

        textColumn10.setColumnName("duracaoHoraNoturna");
        textColumn10.setHeaderColumnName("Duracao Hora Noturna");
        textColumn10.setHeaderFont(new java.awt.Font("Arial", 1, 11));
        textColumn10.setPreferredWidth(130);
        gridControl1.getColumnContainer().add(textColumn10);

        comboColumn11.setColumnName("tratamentoHoraMais");
        comboColumn11.setDomainId("pontoTratamentoHoraMais");
        comboColumn11.setHeaderColumnName("Tratamento Hora Mais");
        comboColumn11.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        comboColumn11.setPreferredWidth(130);
        gridControl1.getColumnContainer().add(comboColumn11);

        comboColumn12.setColumnName("tratamentoHoraMenos");
        comboColumn12.setDomainId("pontoTratamentoHoraMenos");
        comboColumn12.setHeaderColumnName("Tratamento Hora Menos");
        comboColumn12.setHeaderFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        comboColumn12.setPreferredWidth(140);
        gridControl1.getColumnContainer().add(comboColumn12);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn11;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn12;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn8;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn9;
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.InsertButton insertButton1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn4;
    private javax.swing.JPanel jPanel1;
    private org.openswing.swing.client.NavigatorBar navigatorBar1;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn10;
    private org.openswing.swing.table.columns.client.TextColumn textColumn3;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    private org.openswing.swing.table.columns.client.TextColumn textColumn6;
    private org.openswing.swing.table.columns.client.TextColumn textColumn7;
    // End of variables declaration//GEN-END:variables
}
